#!/usr/bin/env python3
from tweepy_modules.modularized_bot import main
import time

maxtries = 8    # 8 * 15 minutes = about 2 hours total of waiting,

for i in range(maxtries):
    try:
        main()
        break
    except:
        time.sleep(900)
        print("fail", i)
